DROP DATABASE IF EXISTS 2024_05_exam_ksk;
CREATE DATABASE 2024_05_exam_ksk;
USE 2024_05_exam_ksk;

CREATE TABLE faq (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    regDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    updateDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    question VARCHAR(255) NOT NULL,
    answer TEXT NOT NULL
);

SELECT * FROM faq WHERE answer LIKE '%택배사%';
SELECT * FROM faq WHERE answer LIKE '%교환%';
SELECT * FROM faq WHERE answer LIKE '%반품%';